##
# Installs and configures the PostgreSQL database
#

- name: ensure postgresql database packages are installed
  apt: name={{item}}
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
    - postgresql-client
    - postgresql-client-common

- name: ensure database is created
  postgresql_db: name={{ app_name }}
  become: yes
  become_user: postgres

- name: configure seperate PostgreSQL user 
  postgresql_user: db={{ app_name}} name={{ db_user }}
                   password={{ db_password }} priv=ALL
                   role_attr_flags=NOSUPERUSER
  become: yes
  become_user: postgres


