##
# updates the APT package cache and install packages
# servers necessary for web. also enables firewall.
##

- apt: update_cache=yes

- name: ensure web server packages are installed
  apt: name={{item}}
  with_items:
    - fail2ban
    - python-dev
    - python-virtualenv

- name: enable SSH in firewall
  ufw: rule=allow port=22

- name: enable HTTP connections for web server 
  ufw: rule=allow port=80

- name: enable HTTPS connections for web server
  ufw: rule=allow port=443

- name: enable firewall
  ufw: state=enabled

