
###
# This playbook deploys the whole application stack in this site.
##

- name: apply common configuration to server
  hosts: all
  become: yes
  become_method: sudo
  user: deployer
  roles:
    - common

